# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180421_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 21, 11, 53, 59, 595172)),
        ),
    ]
