# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 05:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180421_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 5, 34, 50, 978168)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_type',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
