# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 05:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180426_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 26, 5, 35, 28, 100285)),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
